### ISSUE TITLE
Sender name in Push Notification

### ISSUE THREAD

**Issue by umarniz** [senseobservationsystems/ejabberd#12]
I just tried the Push Notifications in the Alpha version of the app and noticed it just has the message body in the Push Notification. It would be great to have the name of the person who sent the message also visible in the Push Notification.

I am not sure if there is an issue for it already or if this is part of the specification @orhan89 @freakinruben

**Comment by freakinruben** [comment]
It was an agreed way of shipping the notifications faster. I agree with your proposal Umar but ejabber doesn’t know usernames right now, only external ids so this requires changes in either product or backend

________________________________
