### ISSUE TITLE
Refactor mod_push specific implementation

### ISSUE THREAD

**Issue by rhariady** [senseobservationsystems/ejabberd#4]
In the process of solving #1, we add the `notify/4` function in `mod_push` and call this function from function `mam_message` and `offline_message` in the same module. This is not the best approach as we put the specific implementation in place that should be generic. There are 2 option that is open to improve this:
1. create separate mod_push_sense that will hook to `pubsub_publish_item` event, and move all the modification that we made there
2. create XMPP Component that will handle the push notification

**Comment by umarniz** [comment]
I would group this task into an epic of unifying Push Notifications and sending them all from a single place

**Comment by rhariady** [comment]
I end up creating a separate [XMPP Component on top of SleekXMPP ](https://github.com/senseobservationsystems/xmpp-push-service) (option 2). When it's done, we can start using the original ejabberd from processone again.

> I would group this task into an epic of unifying Push Notifications and sending them all from a single place 

nice idea! although modifying push module or creating new XMPP component is still required, i still think having this configuration in the end is preferable
